# Generated by Django 4.0.3 on 2022-10-06 05:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_transaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='BetEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_number', models.IntegerField()),
                ('bet_amount', models.IntegerField()),
                ('voter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.profile')),
            ],
        ),
    ]
