# Generated by Django 4.0.3 on 2022-10-06 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_betwin'),
    ]

    operations = [
        migrations.AddField(
            model_name='betentry',
            name='game_id',
            field=models.IntegerField(default=1),
        ),
    ]
