# Generated by Django 4.0.3 on 2022-10-09 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_betentry_game_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='transaction_type',
            field=models.IntegerField(choices=[(1, 'Fillpoints'), (2, 'Playbet'), (3, 'Wonprize')], default=1),
        ),
    ]
