# Generated by Django 4.1.3 on 2022-11-25 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0010_transaction_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.IntegerField(choices=[(1, 'Fillpoints'), (2, 'Playbet'), (3, 'Wonprize'), (4, 'Withdrawpoint')], default=1),
        ),
    ]
