# Generated by Django 4.1.3 on 2022-11-29 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0012_transaction_selected_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NextResult', models.IntegerField(default=20)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
