# Generated by Django 4.1.3 on 2022-11-29 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0013_resultsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultsettings',
            name='BrokerPercent',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='resultsettings',
            name='UserPercent',
            field=models.IntegerField(default=10),
        ),
    ]
